# Generated by Django 4.0.2 on 2022-03-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('albumArtist', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ablumTitle', models.CharField(max_length=255)),
                ('artistName', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('yearProduced', models.CharField(max_length=255)),
                ('explicit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songArtist', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('song', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user')),
            ],
        ),
    ]
