# Generated by Django 4.0.2 on 2022-03-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumInfo',
            new_name='Album',
        ),
    ]
