# Generated by Django 4.0.2 on 2022-03-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_albuminfo_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ablumTitle',
            new_name='albumTitle',
        ),
    ]
